CREATE DATABASE IF NOT EXISTS zenmind_website CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

USE zenmind_website;

CREATE TABLE IF NOT EXISTS auth_user (
  ID_ BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  EMAIL_ VARCHAR(255) NOT NULL DEFAULT '',
  DISPLAY_NAME_ VARCHAR(255) NOT NULL DEFAULT '',
  AVATAR_URL_ VARCHAR(1024) NOT NULL DEFAULT '',
  AUTH_PROVIDER_ VARCHAR(32) NOT NULL DEFAULT 'local',
  AUTH_SUB_ VARCHAR(255) NOT NULL DEFAULT '',
  ROLE_ VARCHAR(32) NOT NULL DEFAULT 'user',
  ENABLED_ TINYINT(1) NOT NULL DEFAULT 1,
  CREATED_AT_ DATETIME(3) NOT NULL,
  UPDATED_AT_ DATETIME(3) NOT NULL,
  LAST_LOGIN_AT_ DATETIME(3) NULL,
  PRIMARY KEY (ID_),
  UNIQUE KEY UK_AUTH_USER_PROVIDER_SUB (AUTH_PROVIDER_, AUTH_SUB_),
  KEY IDX_AUTH_USER_EMAIL (EMAIL_)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS auth_local_credential (
  USER_ID_ BIGINT UNSIGNED NOT NULL,
  PASSWORD_HASH_ VARCHAR(255) NOT NULL,
  PASSWORD_UPDATED_AT_ DATETIME(3) NOT NULL,
  CREATED_AT_ DATETIME(3) NOT NULL,
  PRIMARY KEY (USER_ID_),
  CONSTRAINT FK_AUTH_LOCAL_CREDENTIAL_USER FOREIGN KEY (USER_ID_) REFERENCES auth_user (ID_) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS auth_session (
  ID_ BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  USER_ID_ BIGINT UNSIGNED NOT NULL,
  TOKEN_HASH_ CHAR(64) NOT NULL,
  EXPIRES_AT_ DATETIME(3) NOT NULL,
  CREATED_AT_ DATETIME(3) NOT NULL,
  LAST_SEEN_AT_ DATETIME(3) NOT NULL,
  USER_AGENT_ VARCHAR(512) NOT NULL DEFAULT '',
  IP_ VARCHAR(64) NOT NULL DEFAULT '',
  PRIMARY KEY (ID_),
  UNIQUE KEY UK_AUTH_SESSION_TOKEN_HASH (TOKEN_HASH_),
  KEY IDX_AUTH_SESSION_USER_EXPIRES (USER_ID_, EXPIRES_AT_),
  CONSTRAINT FK_AUTH_SESSION_USER FOREIGN KEY (USER_ID_) REFERENCES auth_user (ID_) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS auth_login_log (
  ID_ BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  USER_ID_ BIGINT UNSIGNED NULL,
  EMAIL_ VARCHAR(255) NOT NULL DEFAULT '',
  DISPLAY_NAME_ VARCHAR(255) NOT NULL DEFAULT '',
  AUTH_METHOD_ VARCHAR(32) NOT NULL,
  LOGIN_RESULT_ VARCHAR(16) NOT NULL,
  FAILURE_REASON_ VARCHAR(128) NOT NULL DEFAULT '',
  IP_ VARCHAR(64) NOT NULL DEFAULT '',
  USER_AGENT_ VARCHAR(512) NOT NULL DEFAULT '',
  LOGIN_AT_ DATETIME(3) NOT NULL,
  PRIMARY KEY (ID_),
  KEY IDX_AUTH_LOGIN_LOG_USER_AT (USER_ID_, LOGIN_AT_),
  KEY IDX_AUTH_LOGIN_LOG_METHOD_AT (AUTH_METHOD_, LOGIN_AT_),
  CONSTRAINT FK_AUTH_LOGIN_LOG_USER FOREIGN KEY (USER_ID_) REFERENCES auth_user (ID_) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
